[project]
repository-type = "tooling"
versioning-scheme = "semver"
branching-model = "library-release"
release-model = "tagged-release"
primary-language = "shell"

[ci]
versions = ["latest"]
integration-tests = false

[workflows.post-merge]
docker-publish = "cd.yml"

[publish]
release = true
docs = true

[dependencies]
vergil = "v2.0"
