# https://github.com/vergil-project/vergil-actions/blob/develop/.github/workflows/README.md
name: CD

on:
  push:
    branches: [develop, main]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  security-events: write
  attestations: write
  id-token: write
  pull-requests: write

jobs:
  docs:
    uses: vergil-project/vergil-actions/.github/workflows/cd-docs.yml@v1.5
    permissions:
      contents: write

  release:
    if: github.ref == 'refs/heads/main'
    uses: vergil-project/vergil-actions/.github/workflows/cd-release.yml@v1.5
    with:
      language: base
      container-tag: latest
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      attestations: write

  docker-publish:
    needs: [release]
    if: always() && (needs.release.result == 'success' || needs.release.result == 'skipped')
    uses: ./.github/workflows/cd-docker-publish.yml
    with:
      image-prefix: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    permissions:
      packages: write
      contents: read
      security-events: write
      attestations: write
      id-token: write
