# https://github.com/vergil-project/vergil-actions/blob/develop/.github/workflows/README.md
name: CI

on:
  pull_request:
  workflow_call:
    inputs:
      run-security:
        type: boolean
        default: true
      run-release:
        type: boolean
        default: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hadolint:
    name: "quality / hadolint"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vergil-project/prod-base:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Generate Dockerfiles from templates
        run: docker/generate.sh

      - name: Run Hadolint
        run: hadolint docker/*/Dockerfile

  quality:
    uses: vergil-project/vergil-actions/.github/workflows/ci-quality.yml@v1.5
    with:
      language: shell
      versions: '["latest"]'
      container-suffix: base

  security:
    uses: vergil-project/vergil-actions/.github/workflows/ci-security.yml@v1.5
    with:
      language: shell
      run-codeql: false
      run-standards: ${{ inputs.run-release != 'false' }}
      run-security: ${{ inputs.run-security != 'false' }}
    permissions:
      contents: read
      security-events: write

  version:
    uses: vergil-project/vergil-actions/.github/workflows/ci-version-bump.yml@v1.5
    with:
      language: shell
      run-release: ${{ inputs.run-release != 'false' }}
